### ISSUE TITLE
Add duplicate detection

### ISSUE THREAD

**Issue by GigsD4X** [F3XTeam/RBX-Building-Tools#29]
Parts that are accidentally cloned and forgotten inside other parts should be highlighted to prevent duplicates.

**Comment by AnonymousPrayers** [comment]
Working on a possible solution.

**Comment by GigsD4X** [comment]
You know how to implement this? Just connect to Selection.ItemAdded, check if there's duplicates (same CFrame), bring up a small, ignorable but noticeable notification GUI that tells you there's duplicates and gives you the option to delete them.

**Comment by AnonymousPrayers** [comment]
Idk how the guis on this thing work.




On Wed, Jul 8, 2015 at 7:32 PM -0700, "Robert" <notifications@github.com> wrote:
You know how to implement this? Just connect to Selection.ItemAdded, check if there's duplicates (same CFrame), bring up a small, ignorable but noticeable notification GUI that tells you there's duplicates and gives you the option to delete them.

---

**Comment by GigsD4X** [comment]
Just create a GUI template, put it under Interfaces, and parent it to the UI root from your code :p

**Comment by AnonymousPrayers** [comment]
Besides, same CFrame doesn't instantly mean duplicate. Checking for same CFrame and same Size would be better. I could have a 5, 1, 1 and a 1, 1, 5 part with the same CFrame (and I have before, too), and it isn't the same part.





On Wed, Jul 8, 2015 at 7:32 PM -0700, "Robert" <notifications@github.com> wrote:
You know how to implement this? Just connect to Selection.ItemAdded, check if there's duplicates (same CFrame), bring up a small, ignorable but noticeable notification GUI that tells you there's duplicates and gives you the option to delete them.

---

**Comment by AnonymousPrayers** [comment]
Here was my original idea...
clone.Archivable = falselocal listener = clone.Changed:connect(function()listener:disconnect()clone.Archivable = trueend)
So it's there, but doesn't save if it remains unchanged. Even checking size and CFrame won't work, as people will occasionally have parts of the same size and CFrame but one not visible, or something like that, intentinally. If it remains unchanged, then you know it's not intentional. I still don't get the GUIs (how to make the template mainly), so yeah. Besides, it might be better if it was automatic.



On Wed, Jul 8, 2015 at 7:35 PM -0700, "Robert" <notifications@github.com> wrote:
Just create a GUI template, put it under Interfaces, and parent it to the UI root from your code :p

---
